name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    -name:  Build with Gradle
     uses:  gradle/gradle-build-actions@67421db6bd0bf253fb4bd25b31ebb98943c375e1
     with:
      arguments:  build